{% set name = "num2words" %}
{% set version = "0.5.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6c684e2220d8adb3612d2c807a9772cc3269963fbcd77f7979b689a77f6043d4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - docopt >=0.6.2
    - python >=2.7

test:
  imports:
    - num2words

about:
  home: https://github.com/savoirfairelinux/num2words
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: Modules to convert numbers to words. Easily extensible.
  dev_url: https://github.com/savoirfairelinux/num2words

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - Tata17
