{% set name = "num2words" %}
{% set version = "0.5.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b066ec18e56b6616a3b38086b5747daafbaa8868b226a36127e0451c0cf379c6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - docopt >=0.6.2
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - num2words

about:
  home: https://github.com/savoirfairelinux/num2words
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: Modules to convert numbers to words. Easily extensible.
  dev_url: https://github.com/savoirfairelinux/num2words

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - Tata17
    - xhochy
